const extToMIME = [
  { name: 'C', mime: 'text/x-csrc', mode: 'clike', ext: ['c', 'h', 'ino'] },
  {
    name: 'C++',
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  {
    name: 'C#',
    mime: 'text/x-csharp',
    mode: 'clike',
    ext: ['cs'],
    alias: ['csharp', 'cs'],
  },
  {
    name: 'CMake',
    mime: 'text/x-cmake',
    mode: 'cmake',
    ext: ['cmake', 'cmake.in'],
    file: /^CMakeLists\.txt$/,
  },
  { name: 'CSS', mime: 'text/css', mode: 'css', ext: ['css'] },
  {
    name: 'Dart',
    mimes: ['application/dart', 'text/x-dart'],
    mode: 'dart',
    ext: ['dart'],
  },
  { name: 'diff', mime: 'text/x-diff', mode: 'diff', ext: ['diff', 'patch'] },
  { name: 'Erlang', mime: 'text/x-erlang', mode: 'erlang', ext: ['erl'] },
  { name: 'Go', mime: 'text/x-go', mode: 'go', ext: ['go'] },
  {
    name: 'Groovy',
    mime: 'text/x-groovy',
    mode: 'groovy',
    ext: ['groovy', 'gradle'],
    file: /^Jenkinsfile$/,
  },
  { name: 'HAML', mime: 'text/x-haml', mode: 'haml', ext: ['haml'] },
  { name: 'Haskell', mime: 'text/x-haskell', mode: 'haskell', ext: ['hs'] },
  {
    name: 'Haskell (Literate)',
    mime: 'text/x-literate-haskell',
    mode: 'haskell-literate',
    ext: ['lhs'],
  },
  {
    name: 'ASP.NET',
    mime: 'application/x-aspx',
    mode: 'htmlembedded',
    ext: ['aspx'],
    alias: ['asp', 'aspx'],
  },
  {
    name: 'HTML',
    mime: 'text/html',
    mode: 'htmlmixed',
    ext: ['html', 'htm', 'handlebars', 'hbs'],
    alias: ['xhtml'],
  },
  { name: 'Java', mime: 'text/x-java', mode: 'clike', ext: ['java'] },
  {
    name: 'Java Server Pages',
    mime: 'application/x-jsp',
    mode: 'htmlembedded',
    ext: ['jsp'],
    alias: ['jsp'],
  },
  {
    name: 'JavaScript',
    mimes: [
      'text/javascript',
      'text/ecmascript',
      'application/javascript',
      'application/x-javascript',
      'application/ecmascript',
    ],
    mode: 'javascript',
    ext: ['js'],
    alias: ['ecmascript', 'js', 'node'],
  },
  {
    name: 'JSON',
    mimes: ['application/json', 'application/x-json'],
    mode: 'javascript',
    ext: ['json', 'map'],
    alias: ['json5'],
  },
  {
    name: 'JSON-LD',
    mime: 'application/ld+json',
    mode: 'javascript',
    ext: ['jsonld'],
    alias: ['jsonld'],
  },
  { name: 'JSX', mime: 'text/jsx', mode: 'jsx', ext: ['jsx'] },
  { name: 'Kotlin', mime: 'text/x-kotlin', mode: 'clike', ext: ['kt'] },
  { name: 'LESS', mime: 'text/x-less', mode: 'css', ext: ['less'] },
  { name: 'Lua', mime: 'text/x-lua', mode: 'lua', ext: ['lua'] },
  {
    name: 'Markdown',
    mime: 'text/x-markdown',
    mode: 'markdown',
    ext: ['markdown', 'md', 'mkd'],
  },
  { name: 'Pascal', mime: 'text/x-pascal', mode: 'pascal', ext: ['p', 'pas'] },
  { name: 'Perl', mime: 'text/x-perl', mode: 'perl', ext: ['pl', 'pm'] },
  {
    name: 'PHP',
    mimes: [
      'text/x-php',
      'application/x-httpd-php',
      'application/x-httpd-php-open',
    ],
    mode: 'php',
    ext: ['php', 'php3', 'php4', 'php5', 'php7', 'phtml'],
  },
  {
    name: 'Plain Text',
    mime: 'text/plain',
    mode: 'null',
    ext: ['txt', 'text', 'conf', 'def', 'list', 'log'],
  },
  {
    name: 'PowerShell',
    mime: 'application/x-powershell',
    mode: 'powershell',
    ext: ['ps1', 'psd1', 'psm1'],
  },
  {
    name: 'Python',
    mime: 'text/x-python',
    mode: 'python',
    ext: ['BUILD', 'bzl', 'py', 'pyw'],
    file: /^(BUCK|BUILD)$/,
  },
  {
    name: 'R',
    mime: 'text/x-rsrc',
    mode: 'r',
    ext: ['r', 'R'],
    alias: ['rscript'],
  },
  {
    name: 'Ruby',
    mime: 'text/x-ruby',
    mode: 'ruby',
    ext: ['rb'],
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
  },
  { name: 'Rust', mime: 'text/x-rustsrc', mode: 'rust', ext: ['rs'] },
  { name: 'Sass', mime: 'text/x-sass', mode: 'sass', ext: ['sass'] },
  { name: 'SCSS', mime: 'text/x-scss', mode: 'css', ext: ['scss'] },
  {
    name: 'Shell',
    mimes: ['text/x-sh', 'application/x-sh'],
    mode: 'shell',
    ext: ['sh', 'ksh', 'bash'],
    alias: ['bash', 'sh', 'zsh'],
    file: /^PKGBUILD$/,
  },
  { name: 'SQL', mime: 'text/x-sql', mode: 'sql', ext: ['sql'] },
  { name: 'Stylus', mime: 'text/x-styl', mode: 'stylus', ext: ['styl'] },
  { name: 'Swift', mime: 'text/x-swift', mode: 'swift', ext: ['swift'] },
  {
    name: 'LaTeX',
    mime: 'text/x-latex',
    mode: 'stex',
    ext: ['text', 'ltx', 'tex'],
    alias: ['tex'],
  },
  { name: 'TOML', mime: 'text/x-toml', mode: 'toml', ext: ['toml'] },
  {
    name: 'TypeScript',
    mime: 'application/typescript',
    mode: 'javascript',
    ext: ['ts'],
    alias: ['ts'],
  },
  {
    name: 'TypeScript-JSX',
    mime: 'text/typescript-jsx',
    mode: 'jsx',
    ext: ['tsx'],
    alias: ['tsx'],
  },
  {
    name: 'Vue.js Component',
    mimes: ['script/x-vue', 'text/x-vue'],
    mode: 'vue',
    ext: ['vue'],
  },
  {
    name: 'XML',
    mimes: ['application/xml', 'text/xml'],
    mode: 'xml',
    ext: ['xml', 'xsl', 'xsd', 'svg'],
    alias: ['rss', 'wsdl', 'xsd'],
  },
  {
    name: 'YAML',
    mimes: ['text/x-yaml', 'text/yaml'],
    mode: 'yaml',
    ext: ['yaml', 'yml'],
    alias: ['yml'],
  },
  {
    name: 'WebAssembly',
    mime: 'text/webassembly',
    mode: 'wast',
    ext: ['wat', 'wast'],
  },
]

export default extToMIME
